Repository antvis/GUI, pull requests merged in 2019-10, with the labels that each got.

#9 fix: use any for slider style props for now
  src/slider/index.ts
Labels: PR: reviewed-changes-requested, bug

#10 feat(slider): 兼容移动端事件
  src/slider/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#12 fix: 更新slider滑块和文本的padding
  package.json
  src/slider/constant.ts
  src/slider/index.ts
Labels: PR: reviewed-approved
