Repository antvis/GUI, pull requests merged in 2021-06, with the labels that each got.

#20 chore: use father-build
  .fatherrc.ts
  package.json
  rollup.config.js
  tsconfig.json
Labels: PR: unreviewed

#19 feat: marker + icon
  .eslintrc.js
  .fatherrc.ts
  __tests__/unit/index.spec.ts
  __tests__/unit/ui/icon/index.spec.ts
  __tests__/unit/ui/marker/index.spec.ts
  __tests__/utils/delay.ts
  __tests__/utils/dom.ts
  __tests__/utils/index.ts
  package.json
  rollup.config.js
  src/index.ts
  src/types.ts
  src/ui/arrow/index.ts
  src/ui/axis/index.ts
  src/ui/button/index.ts
  src/ui/icon/index.ts
  src/ui/icon/types.ts
  src/ui/index.ts
  src/ui/legend/index.ts
  src/ui/marker/index.ts
  src/ui/marker/symbol.ts
  src/ui/marker/types.ts
  src/ui/scrollbar/index.ts
  src/ui/sheet/index.ts
  src/ui/slider/index.ts
  src/ui/spark/index.ts
  src/ui/timeline/index.ts
  src/util/index.ts
  src/util/svg2marker.ts
  tsconfig.json
Labels: PR: unreviewed

#21 feat: add gatsby
  .eslintignore
  .gitignore
  __tests__/unit/ui/icon/index.spec.ts
  __tests__/unit/ui/marker/index.spec.ts
  api-extractor.json
  docs/api/api.en.md
  docs/api/api.zh.md
  docs/api/ui/arrow.en.md
  docs/api/ui/arrow.zh.md
  docs/api/ui/icon.en.md
  docs/api/ui/icon.zh.md
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  examples/icon/basic/API.en.md
  examples/icon/basic/API.zh.md
  examples/icon/basic/demo/meta.json
  examples/icon/basic/demo/triangle.ts
  examples/icon/basic/index.en.md
  examples/icon/basic/index.zh.md
  examples/marker/basic/API.en.md
  examples/marker/basic/API.zh.md
  examples/marker/basic/demo/meta.json
  examples/marker/basic/demo/register-symbol.ts
  examples/marker/basic/demo/triangle.ts
  examples/marker/basic/index.en.md
  examples/marker/basic/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  jest.setup.js
  package.json
  site/locale.json
  site/pages/index.en.tsx
  site/pages/index.less
  site/pages/index.zh.tsx
Labels: PR: partially-approved

#23 chore: 版本问题,各自引入 babel-polyfill
  __tests__/unit/ui/icon/index.spec.ts
  __tests__/unit/ui/marker/index.spec.ts
  jest.setup.js
  package.json
Labels: PR: reviewed-approved

#22 Feat button
  .gitignore
  __tests__/unit/ui/button/disabled.spec.ts
  __tests__/unit/ui/button/index.spec.ts
  __tests__/unit/ui/icon/index.spec.ts
  __tests__/unit/ui/marker/index.spec.ts
  __tests__/unit/util/text.spec.ts
  docs/api/ui/button.en.md
  docs/api/ui/button.zh.md
  examples/button/basic/API.en.md
  examples/button/basic/API.zh.md
  examples/button/basic/demo/custom-button.ts
  examples/button/basic/demo/disabled-button.ts
  examples/button/basic/demo/meta.json
  examples/button/basic/demo/simple-button.ts
  examples/button/basic/index.en.md
  examples/button/basic/index.zh.md
  jest.setup.js
  package.json
  src/index.ts
  src/ui/button/constant.ts
  src/ui/button/index.ts
  src/ui/button/types.ts
  src/util/index.ts
  src/util/text.ts
Labels: PR: reviewed-approved

#26 chore: changed ./github/build.yml runs on macos
  .github/workflows/build.yml
  __tests__/unit/util/text.spec.ts
  package.json
Labels: PR: reviewed-approved
